FIRST_BOOK_NAME = "Name1"
SECOND_BOOK_NAME = "Name2"
THIRD_BOOK_NAME = "Name3"

FIRST_AUTHOR_NAME = "Author1"
SECOND_AUTHOR_NAME = "Author2"
THIRD_AUTHOR_NAME = "Author3"

FIRST_BOOK_PAGES = 200
SECOND_BOOK_PAGES = 250
THIRD_BOOK_PAGES = 300

FIRST_BOOK_ISBN = 100000
SECOND_BOOK_ISBN = 100001
THIRD_BOOK_ISBN = 100002

FIRST_USER_PERSONAL_NUMBER = 1
SECOND_USER_PERSONAL_NUMBER = 2
THIRD_USER_PERSONAL_NUMBER = 3

FIRST_USER_NAME = "User1"
SECOND_USER_NAME = "User2"
THIRD_USER_NAME = "User3"

FIRST_USER_SURNAME = "Surname1"
SECOND_USER_SURNAME = "Surname2"
THIRD_USER_SURNAME = "Surname3"
